services:
  postgres:
    image: postgres:16-alpine
    container_name: fintech_db
    environment:
      POSTGRES_USER: fintech_user
      POSTGRES_PASSWORD: fintech_password
      POSTGRES_DB: fintech_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fintech_user -d fintech_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
